# Generated by Django 3.2.4 on 2021-06-12 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfProducts', models.CharField(max_length=200)),
                ('ProductIDs', models.CharField(default='', max_length=200)),
                ('TotalPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('avatar', models.CharField(default='', max_length=200)),
                ('nborders', models.IntegerField(default='0')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='globalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tropical Deliveries', max_length=200)),
                ('year', models.CharField(default='2021', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('openinghours', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOngoing', models.CharField(default='', max_length=200)),
                ('DeliveryArea', models.CharField(default='', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, default='', null=True)),
                ('CartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('CostumerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, default='', null=True)),
                ('issue', models.TextField(default='', max_length=500)),
                ('CartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('CostumerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.costumer')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='CostumerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.costumer'),
        ),
    ]
